version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app         # Esto monta tu código fuente local
      - ./db:/app/db   # Asegura persistencia de la base de datos
    environment:
      - NODE_ENV=development